#!/bin/bash

### VARIABLES ###

script_dir="$(dirname "$(realpath $0)")"
name="$(logname)"
progs="$script_dir/progs.list"
dotfiles="git://git.cybvik.xyz/dotfiles"
src="/home/$name/.local/src"
giturl="git://git.cybvik.xyz"
logfile="/tmp/zerog.log"

# Repos for AUR programs
mwrepo="https://aur.archlinux.org/mutt-wizard-git.git"
syntaxrepo="https://aur.archlinux.org/zsh-fast-syntax-highlighting.git"

### FUNCTIONS ###

warning() { # Write to logfile
    printf "WARNING: $1\n" >> "$logfile"
}

error() { # Write to logfile and exit script
    printf "ERROR: $1\n" >> "$logfile"
    clear
    printf "Error: $1\n"
    exit 1
}
prepare() {
    printf "Preparing...\n"
    printf "Refreshing keys...\n(This will take a while!)\n"
    # Refresh keyring and update keyrings
    pacman-key --refresh >/dev/null 2>&1 ||
	{ warning "Could not refresh keys"; return 1; }
    pacman -Sy --noconfirm archlinux-keyring archlinuxarm-keyring \
	parabola-keyring >/dev/null 2>&1 ||
	{ warning "Could not install keyrings"; return 1; }
    # Install some essential programs
    pacman -S --noconfirm --needed git zsh ca-certificates >/dev/null 2>&1 ||
	{ warning "Initial installs failed"; return 1; }
    # Enable parallel downloads and make pacman look nice
    grep -q "ILoveCandy" /etc/pacman.conf ||
	sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
    sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf
}

install_programs() { # Read from progs.list and install each entry
    printf "### Installing from progs.list ###\n"
    while read -r program; do
	printf "Installing $program\n"
        pacman -S --noconfirm --needed  "$program" >/dev/null 2>&1 ||
	    warning "$program could not be installed"
    done < "$progs"
}

get_dotfiles() { # Download dotfiles and place them in $HOME
    printf "### Installing dotfiles ###\n"
    sudo -u "$name" git clone "$dotfiles" /tmp/dotfiles >/dev/null 2>&1 ||
	{ warning "Could not clone dotfiles"; return 1; }
    sudo -u "$name" cp -rfT /tmp/dotfiles "/home/$name" >/dev/null 2>&1
}

suckless() { # Clone and install suckless programs
    printf "### Installing suckless software ###\n"
    for program in dwm st dmenu slock; do
	cd "$src"
	printf "Installing $program\n"
	sudo -u "$name" git clone "$giturl/$program-cybvik" >/dev/null 2>&1 ||
	    { warning "Could not clone $program"; return 1; }
	cd "$program" && make clean install >/dev/null 2>&1 ||
	    { warning "Could not install $program"; return 1; }
    done
}

git_install() { # Basically a temporary AUR helper
    sudo -u "$name" git clone "$2" /tmp/"$1" >/dev/null 2>&1 ||
	{ warning "Could not clone from AUR ($2)"; return 1; }
    cd /tmp/"$1"
    yes | sudo -u "$name" LANG=C makepkg -si >/dev/null 2>&1 ||
	{ warning "Could not makepkg $2"; return 1; }
}

follow_up() {
    printf "### Finishing touches ###\n"
    # Make zsh the default shell
    chsh -s /bin/zsh "$name" >/dev/null 2>&1
    # Create some needed dirs
    sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"
    sudo -u "$name" mkdir -p "/home/$name/.config/mpd/playlists/"
    # Turn off the computer beep
    rmmod pcspkr
    printf "blacklist pcspkr\n" >/etc/modprobe.d/nobeep.conf
    # Get rid of no longer needed bash files
    yes | rm /home/$name/.bash*
    # Add some services to default runtime
    rc-update add avahi-daemon default >/dev/null
    rc-update add cupsd default >/dev/null
    rc-update add tor default >/dev/null
}

### SCRIPT ###

printf "###########################\n########## ZEROG ##########\n###########\
################\n"

prepare ||
    error "Please make sure that you have a working internet connection and \
you run ZEROG with sudo!"

install_programs

get_dotfiles ||
    error "Could not install dotfiles"

suckless ||
    error "Could not install suckless programs"

# Git installs are disabled by default so you can choose if you want to install
# these packages from the AUR
#
# for repo in "$mwrepo" "$syntaxrepo"; do
#     git_install "$repo"
# done

follow_up ||
    error "Follow up function failed"

printf "###########################\n########## ZEROG ##########\n###########\
################\nZEROG flight finished. Log in again and run 'startx' to \
start your new system\nIf you liked this script, want to report bugs/issues \
or contribute to it, let me know via mail <zerog@cybvik.xyz>\n"
